version: 2.4.1.{build}
configuration: Release
init:
- ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME".TrimStart("v") }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  SnkSecret:
    secure: Mpa4faeUiC2uggKSC5ZgiA==
cache:
- src\packages -> **\packages.config
install:
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe
- ps: nuget install secure-file -ExcludeVersion
before_build:
- ps: nuget restore .\src\couchbase-net-client.sln
- ps: .\secure-file\tools\secure-file.exe -decrypt .\build-utils\Couchbase.snk.enc -secret $env:SnkSecret -out .\Couchbase.snk
- ps: Copy-Item .\Couchbase.snk .\Src\Couchbase\Couchbase.snk
- ps: Copy-Item .\Couchbase.snk .\Src\Couchbase.NetStandard\Couchbase.snk
- ps: Get-Content .\src\Couchbase\Properties\AssemblyInfo.cs | Where { $_ -notmatch "InternalsVisibleTo" } | Out-File .\src\Couchbase\Properties\AssemblyInfo.cs
build_script:
- cmd: msbuild Src\Couchbase\Couchbase.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Couchbase.snk
- cmd: msbuild Src\Couchbase.NetStandard\Couchbase.NetStandard.csproj /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=Couchbase.snk
after_build:
- ps: Copy-Item -Path .\Src\Couchbase\bin\Release -Filter "Couchbase.*" -Destination .\binaries\net45 -Recurse
- ps: Copy-Item -Path .\Src\Couchbase.NetStandard\bin\Release -Filter "Couchbase.*" -Destination .\binaries\netstandard1.5 -Recurse
- ps: Compress-Archive -Path .\binaries\* -CompressionLevel Optimal -DestinationPath .\Couchbase-Net-Client-$env:APPVEYOR_BUILD_VERSION.zip
- ps: nuget pack .\src\Couchbase\Couchbase.nuspec -Properties "Configuration=Release;Platform=AnyCPU;" -version "$env:APPVEYOR_BUILD_VERSION"
artifacts:
- path: '*.zip'
- path: '*.nupkg'
test: off
deploy:
- provider: GitHub
  artifact: /.*\.zip/
  auth_token:
    secure: SKZPuqPpuYCGDlPa2hEJ6NmjNBWJ9J60/kM7Y5cEtvm3EHrYX5j3VhV2KV5os5gA
  on:
    appveyor_repo_tag: true
- provider: S3
  access_key_id:
    secure: suuUVO/OK/7edFaS0HYlm9ouHqd4SIMt8FAE/iAnRR4=
  secret_access_key:
    secure: Nh6AbaBk7P++ymDgtuY7OmkGoXR8s1X+lm5sIZ2Ao39Bw52HLhuPoqy8O3DsgMTQ
  bucket: packages.couchbase.com
  folder: clients/net/2.4/
  artifact: /.*\.zip/
  set_public: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/couchbasenetclient/api/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  server: hhttps://www.nuget.org/api/v2/package
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
