image: Visual Studio 2017
environment:
  SnkSecret:
    secure: Mpa4faeUiC2uggKSC5ZgiA==
cache:
- src\packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache'
- '%LocalAppData%\NuGet\v3-cache'
build_script:
- ps: .\build-utils\Build.ps1
artifacts:
- path: '*.zip'
- path: '*.nupkg'
test: off
deploy:
- provider: S3
  access_key_id:
    secure: d3wpee/z6nV/NH8gMd6dEW1sS/z1k1SIpdYheMSoE3k=
  secret_access_key:
    secure: 8qvahmXRlwR+UOBtl5fjJNDaCPlf1++8YwpcSKu3qAfSRU0XQz+MoYyVQ4U0N01Y
  bucket: packages.couchbase.com
  folder: clients/net/2.5/
  artifact: /.*\.zip/
  set_public: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/couchbasenetclient/api/v2/package
  symbol_server: https://www.myget.org/F/couchbasenetclient/symbols/v2/package
  api_key:
    secure: Cov0c7H0EvTAcF+4heoatFrtbFVvnz9PR0bTNbDKVTjcN47Vy1k2C3Siep6NsdA7
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: false
- provider: NuGet
  api_key:
    secure: RR63qaRziTfBDzeAHNLX/nNGavXrfzgXnSRniyuFgK493SzEw8DUa89bgVZHYSg8
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
